#!/bin/sh

if [[ ! -z $(git status -s) ]]; then
  find . -name "*.md" -not -path "./subprojects/*" -not -path "./.tests/*" | xargs git add
  git commit -m "chore(docs): generate markdown from norg files"
fi
